<button id="alert-button">Click Me</button>

<script type="text/x-magento-init">
{
    "*": {
        "glowAlert": {},
        "cartAlert": {}
    }
}
</script>

<!-- <button id="alert-button2">Click Me 2</button>
<script type="text/javascript">
    require(['jquery', 'sweetalert2'], function ($, Swal) {
        $('#alert-button2').on('click', function () {
            Swal.fire({
                title: 'Success!',
                text: 'SweetAlert2 is working in Magento 2!',
                icon: 'success',
                confirmButtonText: 'Cool'
            });
        });
    });
</script> -->
