<?php
/** @var \JSN\GlowAlert\Helper\Data $helper */
$helper = $this->helper('JSN\GlowAlert\Helper\Data');
?>

<?php if (in_array('add_to_cart', $helper->getAlertLocations())): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "cartAlert": {}
            }
        }
    </script>
<?php endif; ?>

<?php if (in_array('minicart', $helper->getAlertLocations())): ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "minicartAlert": {}
            }
        }
    </script>
<?php endif; ?>
